<?php

// Font Awesome Icons (4.x)
//
$iconFontOption = array(array('', '0'),
						array('Web Application', '--div--'),
						array('Adjust', 'adjust'),
						array('Anchor', 'anchor'),
						array('Archive', 'archive'),
						array('Arrow circle down', 'arrow-circle-o-down'),
						array('Asterisk', 'asterisk'),
						array('Ban circle', 'ban'),
						array('Bar chart', 'bar-chart-o'),
						array('Barcode', 'barcode'),
						array('Beaker', 'flask'),
						array('Beer', 'beer'),
						array('Bell', 'bell-o'),
						array('Bell 2', 'bell'),
						array('Bolt', 'bolt'),
						array('Book', 'book'),
						array('Bookmark', 'bookmark'),
						array('Bookmark empty', 'bookmark-o'),
						array('Briefcase', 'briefcase'),
						array('Bug', 'bug'),
						array('Building', 'building'),
						array('Bullhorn', 'bullhorn'),
						array('Bullseye', 'bullseye'),
						array('Calendar', 'calendar'),
						array('Calendar empty', 'calendar-o'),
						array('Camera', 'camera'),
						array('Camera-retro', 'camera-retro'),
						array('Caret square down', 'caret-square-o-down'),
						array('Caret square up', 'caret-square-o-up'),
						array('Certificate', 'certificate'),
						array('Check', 'check-square-o'),
						array('Check', 'check'),
						array('Check circle', 'check-circle-o'),
						array('Check sign', 'check-circle'),
						array('Check sign', 'check-square'),
						array('Circle', 'circle'),
						array('Circle blank', 'circle-o'),
						array('Clock', 'clock-o'),
						array('Cloud', 'cloud'),
						array('Cloud download', 'cloud-download'),
						array('Cloud upload', 'cloud-upload'),
						array('Code', 'code'),
						array('Code fork', 'code-fork'),
						array('Coffee', 'coffee'),
						array('Cog', 'cog'),
						array('Cogs', 'cogs'),
						array('Collapse', 'collapse-o'),
						array('Comment', 'comment'),
						array('Comment 2', 'comment-o'),
						array('Comments', 'comments'),
						array('Comments 2', 'comments-o'),
						array('Compass', 'compass'),
						array('Credit card', 'credit-card'),
						array('Crop', 'crop'),
						array('Crosshairs', 'crosshairs'),
						array('Cutlery', 'cutlery'),
						array('Desktop', 'desktop'),
						array('Download', 'download'),
						array('Ellipsis horizontal', 'ellipsis-horizontal'),
						array('Ellipsis vertical', 'ellipsis-vertical'),
						array('Envelope', 'envelope'),
						array('Envelope-alt', 'envelope-o'),
						array('Eraser', 'eraser'),
						array('Exchange', 'exchange'),
						array('Exclamation', 'exclamation'),
						array('Exclamation sign', 'exclamation-circle'),
						array('Exclamation triangle', 'exclamation-triangle'),
						array('Expand', 'caret-square-o-right'),
						array('Expand-alt', 'expand-o'),
						array('External link', 'external-link'),
						array('External link sign', 'external-link-square'),
						array('Eye close', 'eye-slash'),
						array('Eye', 'eye'),
						array('Female', 'female'),
						array('Fighter jet', 'fighter-jet'),
						array('Film', 'film'),
						array('Filter', 'filter'),
						array('Fire', 'fire'),
						array('Fire extinguisher', 'fire-extinguisher'),
						array('Flag', 'flag'),
						array('Flag 2', 'flag-o'),
						array('Flag', 'flag-checkered'),
						array('Folder close', 'folder'),
						array('Folder close 2', 'folder-o'),
						array('Folder open', 'folder-open'),
						array('Folder open 2', 'folder-open-o'),
						array('Frown', 'frown-o'),
						array('Gamepad', 'gamepad'),
						array('Gift', 'gift'),
						array('Glass', 'glass'),
						array('Globe', 'globe'),
						array('Group', 'group'),
						array('HDD', 'hdd-o'),
						array('Headphones', 'headphones'),
						array('Heart', 'heart'),
						array('Heart empty', 'heart-o'),
						array('Home', 'home'),
						array('Inbox', 'inbox'),
						array('Info', 'info'),
						array('Info sign', 'info-circle'),
						array('Key', 'key'),
						array('Keyboard', 'keyboard-o'),
						array('Laptop', 'laptop'),
						array('Leaf', 'leaf'),
						array('Legal', 'gavel'),
						array('Lemon', 'lemon-o'),
						array('Level down', 'level-down'),
						array('Level up', 'level-up'),
						array('Lightbulb', 'lightbulb-o'),
						array('Location arrow', 'location-arrow'),
						array('Lock', 'lock'),
						array('Magic', 'magic'),
						array('Magnet', 'magnet'),
						array('Mail reply all', 'mail-reply-all'),
						array('Male', 'male'),
						array('Map marker', 'map-marker'),
						array('Meh', 'meh-o'),
						array('Microphone', 'microphone'),
						array('Microphone slash', 'microphone-slash'),
						array('Minus', 'minus'),
						array('Minus square', 'minus-square-o'),
						array('Minus sign', 'minus-circle'),
						array('Minus sign 2', 'minus-square'),
						array('Mobile', 'mobile'),
						array('Money', 'money'),
						array('Moon', 'moon-o'),
						array('Move', 'move'),
						array('Music', 'music'),
						array('Pencil', 'pencil'),
						array('Pencil', 'pencil-square-o'),
						array('Pencil square', 'pencil-square'),
						array('Phone', 'phone'),
						array('Phone sign', 'phone-square'),
						array('Picture', 'picture-o'),
						array('Plane', 'plane'),
						array('Plus', 'plus'),
						array('Plus sign', 'plus-circle'),
						array('Plus sign 2', 'plus-square'),
						array('Power off', 'power-off'),
						array('Print', 'print'),
						array('Puzzle piece', 'puzzle-piece'),
						array('Qrcode', 'qrcode'),
						array('Question', 'question'),
						array('Question sign', 'question-circle'),
						array('Quote left', 'quote-left'),
						array('Quote right', 'quote-right'),
						array('Random', 'random'),
						array('Refresh', 'refresh'),
						array('Reorder', 'reorder'),
						array('Reply', 'reply'),
						array('Reply all', 'reply-all'),
						array('Resize horizontal', 'resize-horizontal'),
						array('Resize vertical', 'resize-vertical'),
						array('Retweet', 'retweet'),
						array('Road', 'road'),
						array('Rocket', 'rocket'),
						array('RSS', 'rss'),
						array('RSS sign', 'rss-square'),
						array('Search', 'search'),
						array('Share', 'share'),
						array('Share 2', 'share'),
						array('Share sign', 'share-square'),
						array('Shield', 'shield'),
						array('Shopping cart', 'shopping-cart'),
						array('Sign blank', 'square'),
						array('Signal', 'signal'),
						array('Signin', 'sign-in'),
						array('Signout', 'sign-out'),
						array('Sitemap', 'sitemap'),
						array('Smile', 'smile-o'),
						array('Sort', 'sort'),
						array('Sort by alpha', 'sort-alpha-asc'),
						array('Sort by alpha 2', 'sort-alpha-desc'),
						array('Sort by attrib', 'sort-amount-asc'),
						array('Sort by attrib 2', 'sort-amount-desc'),
						array('Sort by order', 'sort-numeric-asc'),
						array('Sort by order 2', 'sort-numeric-desc'),
						array('Sort down', 'sort-asc'),
						array('Sort up', 'sort-desc'),
						array('Spinner', 'spinner'),
						array('Square', 'square-o'),
						array('Star', 'star'),
						array('Star empty', 'star-o'),
						array('Star half', 'star-half'),
						array('Star half empty', 'star-half-o'),
						array('Subscript', 'subscript'),
						array('Suitcase', 'suitcase'),
						array('Sun', 'sun-o'),
						array('Superscript', 'superscript'),
						array('Tablet', 'tablet'),
						array('Tachometer', 'tachometer'),
						array('Tag', 'tag'),
						array('Tags', 'tags'),
						array('Tasks', 'tasks'),
						array('Terminal', 'terminal'),
						array('Thumbs down', 'thumbs-down'),
						array('Thumbs down 2', 'thumbs-o-down'),
						array('Thumbs up', 'thumbs-up'),
						array('Thumbs up 2', 'thumbs-o-up'),
						array('Thumb tack', 'thumb-tack'),
						array('Ticket', 'ticket'),
						array('Times', 'times'),
						array('Times circle', 'times-circle-o'),
						array('Times sign', 'times-circle'),
						array('Tint', 'tint'),
						array('Trash', 'trash-o'),
						array('Trophy', 'trophy'),
						array('Truck', 'truck'),
						array('Umbrella', 'umbrella'),
						array('Unlock', 'unlock'),
						array('Unlock 2', 'unlock-o'),
						array('Upload', 'arrow-circle-o-up'),
						array('Upload 2', 'upload'),
						array('User', 'user'),
						array('Video camera', 'video-camera'),
						array('Volume down', 'volume-down'),
						array('Volume off', 'volume-off'),
						array('Volume up', 'volume-up'),
						array('Wrench', 'wrench'),
						array('Zoom in', 'search-plus'),
						array('Zoom out', 'search-minus'),
						array('Text Editor', '--div--'),
						array('Align center', 'align-center'),
						array('Align justify', 'align-justify'),
						array('Align left', 'align-left'),
						array('Align right', 'align-right'),
						array('Bold', 'bold'),
						array('Clipboard', 'clipboard'),
						array('Columns', 'columns'),
						array('Scissors', 'scissors'),
						array('Eraser', 'eraser'),
						array('File', 'file'),
						array('File 2', 'file-o'),
						array('File text', 'file-text'),
						array('File text 2', 'file-text-o'),
						array('Files', 'files-o'),
						array('Floppy', 'floppy-o'),
						array('Font', 'font'),
						array('Indent left', 'outdent'),
						array('Indent right', 'indent'),
						array('Italic', 'italic'),
						array('Link', 'link'),
						array('List', 'list'),
						array('List 2', 'list-alt'),
						array('Ordered List', 'list-ol'),
						array('Unordered List', 'list-ul'),
						array('Paper clip', 'paperclip'),
						array('Repeat', 'repeat'),
						array('Strike through', 'strikethrough'),
						array('Table', 'table'),
						array('Text height', 'text-height'),
						array('Text width', 'text-width'),
						array('Table header', 'th'),
						array('Table header large', 'th-large'),
						array('Table header list', 'th-list'),
						array('Underline', 'underline'),
						array('Undo', 'undo'),
						array('Unlink', 'chain-broken'),
						array('Directional', '--div--'),
						array('Angle down', 'angle-down'),
						array('Angle left', 'angle-left'),
						array('Angle right', 'angle-right'),
						array('Angle up', 'angle-up'),
						array('Arrow down', 'arrow-down'),
						array('Arrow left', 'arrow-left'),
						array('Arrow right', 'arrow-right'),
						array('Arrow up', 'arrow-up'),
						array('Caret down', 'caret-down'),
						array('Caret left', 'caret-left'),
						array('Caret right', 'caret-right'),
						array('Caret up', 'caret-up'),
						array('Chevron down', 'chevron-down'),
						array('Chevron left', 'chevron-left'),
						array('Chevron right', 'chevron-right'),
						array('Chevron sign down', 'chevron-circle-down'),
						array('Chevron sign left', 'chevron-circle-left'),
						array('Chevron sign right', 'chevron-circle-right'),
						array('Chevron sign up', 'chevron-circle-up'),
						array('Chevron up', 'chevron-up'),
						array('Circle arrow down', 'arrow-circle-down'),
						array('Circle arrow left', 'arrow-circle-left'),
						array('Circle arrow right', 'arrow-circle-right'),
						array('Circle arrow up', 'arrow-circle-up'),
						array('Double angle down', 'angle-double-down'),
						array('Double angle left', 'angle-double-left'),
						array('Double angle right', 'angle-double-right'),
						array('Double angle up', 'angle-double-up'),
						array('Hand down', 'hand-o-down'),
						array('Hand left', 'hand-o-left'),
						array('Hand right', 'hand-o-right'),
						array('Hand up', 'hand-o-up'),
						array('Long arrow down', 'long-arrow-down'),
						array('Long arrow left', 'long-arrow-left'),
						array('Long arrow right', 'long-arrow-right'),
						array('Long arrow up', 'long-arrow-up'),
						array('Video Player', '--div--'),
						array('Backwards', 'backward'),
						array('Eject', 'eject'),
						array('Fast backwards', 'fast-backward'),
						array('Fast forward', 'fast-forward'),
						array('Forward', 'forward'),
						array('Fullscreen', 'fullscreen'),
						array('Pause', 'pause'),
						array('Play', 'play'),
						array('Play (circle)', 'play-circle'),
						array('Play (sign)', 'play-circle'),
						array('Resize full', 'resize-full'),
						array('Resize small', 'resize-small'),
						array('Step backward', 'step-backward'),
						array('Step forward', 'step-forward'),
						array('Stop', 'stop'),
						array('Youtube play', 'youtube-play'),
						array('Currencies', '--div--'),
						array('Euro', 'eur'),
						array('US Dollar', 'usd'),
						array('UK Pounds', 'gbp'),
						array('Japan Yen', 'jpy'),
						array('Chinese Reminbi', 'cny'),
						array('India Rubee', 'inr'),
						array('Korea Won', 'krw'),
						array('Bitcoin', 'btc'),
						array('Brand', '--div--'),
						array('Adn', 'adn'),
						array('Android', 'android'),
						array('Apple', 'apple'),
						array('Bitbucket', 'bitbucket'),
						array('Bitbucket sign', 'bitbucket-square'),
						array('CSS3', 'css3'),
						array('Dribble', 'dribbble'),
						array('Dropbox', 'dropbox'),
						array('Facebook', 'facebook'),
						array('Facebook sign', 'facebook-square'),
						array('Flickr', 'flickr'),
						array('Foursquare', 'foursquare'),
						array('Github', 'github'),
						array('Github 2', 'github-alt'),
						array('Github sign', 'github-square'),
						array('GitTip', 'gittip'),
						array('Google+', 'google-plus'),
						array('Google+ sign', 'google-plus-square'),
						array('HTML5', 'html5'),
						array('Instagram', 'instagram'),
						array('LinkedIn', 'linkedin'),
						array('LinkedIn sign', 'linkedin-square'),
						array('Linux', 'linux'),
						array('MaxCDN', 'maxcdn'),
						array('Pinterest', 'pinterest'),
						array('Pinterest sign', 'pinterest-square'),
						array('Renren', 'renren'),
						array('Skype', 'skype'),
						array('StackExchange', 'stackexchange'),
						array('Trello', 'trello'),
						array('Tumblr', 'tumblr'),
						array('Tumblr sign', 'tumblr-square'),
						array('Twitter', 'twitter'),
						array('Twitter sign', 'twitter-square'),
						array('VK', 'vk'),
						array('Weibo', 'weibo'),
						array('Windows', 'windows'),
						array('Xing', 'xing'),
						array('Xing sign', 'xing-square'),
						array('YouTube', 'youtube'),
						array('YouTube play', 'youtube-play'),
						array('YouTube sign', 'youtube-square'),
						array('Medical', '--div--'),
						array('Ambulance', 'ambulance'),
						array('H-Square', 'h-square'),
						array('Hospital', 'hospital'),
						array('MedKit', 'medkit'),
						array('Stethoscope', 'stethoscope'),
						array('User MD', 'user-md')
);

// add to globals (used in bootstrap_links)
$GLOBALS['iconFontOption'] = $iconFontOption;

?>